package com.cubead.clm.io.weixin.data;

// Generated 2017-5-20 18:03:09 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import com.cubead.clm.io.JSONBUserType;

/**
 * ArticleTotal generated by hbm2java
 */
@Entity
@Table(name = "article_total")
@TypeDef(name = "jsonb", typeClass = JSONBUserType.class)
public class ArticleTotal implements java.io.Serializable {

	private long id;
	private String appid;
	private Date refDate;
	private String msgid;
	private String title;
	private Integer firstDayStatDate;
	private String details;

	public ArticleTotal() {
	}

	public ArticleTotal(long id, String appid) {
		this.id = id;
		this.appid = appid;
	}

	public ArticleTotal(long id, String appid, Date refDate, String msgid,
			String title, Integer firstDayStatDate, String details) {
		this.id = id;
		this.appid = appid;
		this.refDate = refDate;
		this.msgid = msgid;
		this.title = title;
		this.firstDayStatDate = firstDayStatDate;
		this.details = details;
	}

	@Id
	@SequenceGenerator(name="article_total_sequence",sequenceName="article_total_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="article_total_sequence")	
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "appid", nullable = false)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ref_date", length = 13)
	public Date getRefDate() {
		return this.refDate;
	}

	public void setRefDate(Date refDate) {
		this.refDate = refDate;
	}

	@Column(name = "msgid")
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "first_day_stat_date")
	public Integer getFirstDayStatDate() {
		return this.firstDayStatDate;
	}

	public void setFirstDayStatDate(Integer firstDayStatDate) {
		this.firstDayStatDate = firstDayStatDate;
	}
	
	@Type(type = "jsonb")
	@Column(name = "details")
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

}
