package com.cubead.clm.io.weixin.data;

// Generated 2017-5-20 18:03:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CumulateUser generated by hbm2java
 */
@Entity
@Table(name = "cumulate_user")
public class CumulateUser implements java.io.Serializable {

	private long id;
	private String appid;
	private Integer cumulateUser;
	private Date refDate;

	public CumulateUser() {
	}

	public CumulateUser(long id, String appid) {
		this.id = id;
		this.appid = appid;
	}

	public CumulateUser(long id, String appid, Integer cumulateUser,
			Date refDate) {
		this.id = id;
		this.appid = appid;
		this.cumulateUser = cumulateUser;
		this.refDate = refDate;
	}

	@Id
	@SequenceGenerator(name="cumulate_user_sequence",sequenceName="cumulate_user_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="cumulate_user_sequence")	
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "appid", nullable = false)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "cumulate_user")
	public Integer getCumulateUser() {
		return this.cumulateUser;
	}

	public void setCumulateUser(Integer cumulateUser) {
		this.cumulateUser = cumulateUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ref_date", length = 13)
	public Date getRefDate() {
		return this.refDate;
	}

	public void setRefDate(Date refDate) {
		this.refDate = refDate;
	}

}
