package com.cubead.clm.io.weixin.data;

// Generated 2017-5-20 18:03:09 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import com.cubead.clm.io.JSONBUserType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info")
@TypeDef(name = "jsonb", typeClass = JSONBUserType.class)
public class UserInfo implements java.io.Serializable {

	private long id;
	private String appid;
	private String nickName;
	private Integer serviceTypeInfo;
	private Integer verifyTypeInfo;
	private String userName;
	private String principalName;
	private String alias;
	private String businessInfo;
	private String qrcodeUrl;
	private String funcInfo;
	private String headImg;

	public UserInfo() {
	}

	public UserInfo(long id, String appid) {
		this.id = id;
		this.appid = appid;
	}

	public UserInfo(long id, String appid, String nickName,
			Integer serviceTypeInfo, Integer verifyTypeInfo, String userName,
			String principalName, String alias, String businessInfo,
			String qrcodeUrl, String funcInfo, String headImg) {
		this.id = id;
		this.appid = appid;
		this.nickName = nickName;
		this.serviceTypeInfo = serviceTypeInfo;
		this.verifyTypeInfo = verifyTypeInfo;
		this.userName = userName;
		this.principalName = principalName;
		this.alias = alias;
		this.businessInfo = businessInfo;
		this.qrcodeUrl = qrcodeUrl;
		this.funcInfo = funcInfo;
		this.headImg = headImg;
	}

	@Id
	@SequenceGenerator(name="user_info_sequence",sequenceName="user_info_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="user_info_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "appid", nullable = false)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "nick_name")
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "service_type_info")
	public Integer getServiceTypeInfo() {
		return this.serviceTypeInfo;
	}

	public void setServiceTypeInfo(Integer serviceTypeInfo) {
		this.serviceTypeInfo = serviceTypeInfo;
	}

	@Column(name = "verify_type_info")
	public Integer getVerifyTypeInfo() {
		return this.verifyTypeInfo;
	}

	public void setVerifyTypeInfo(Integer verifyTypeInfo) {
		this.verifyTypeInfo = verifyTypeInfo;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "principal_name")
	public String getPrincipalName() {
		return this.principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}

	@Column(name = "alias")
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Type(type = "jsonb")
	@Column(name = "business_info")
	public String getBusinessInfo() {
		return this.businessInfo;
	}

	public void setBusinessInfo(String businessInfo) {
		this.businessInfo = businessInfo;
	}

	@Column(name = "qrcode_url")
	public String getQrcodeUrl() {
		return this.qrcodeUrl;
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		this.qrcodeUrl = qrcodeUrl;
	}

	@Type(type = "jsonb")
	@Column(name = "func_info")
	public String getFuncInfo() {
		return this.funcInfo;
	}

	public void setFuncInfo(String funcInfo) {
		this.funcInfo = funcInfo;
	}

	@Column(name = "head_img")
	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

}
